
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\fredr\Desktop\Prosjekter\NewPassManager\build\assets\frame3")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1800x900")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 900,
    width = 1800,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    914.0,
    461.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    917.0,
    195.0,
    image=image_image_2
)

canvas.create_rectangle(
    437.0,
    264.0,
    1362.0,
    874.0,
    fill="#A3B939",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=631.0,
    y=686.0,
    width=264.0,
    height=65.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=900.0,
    y=687.0,
    width=264.0,
    height=65.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=768.0,
    y=764.0,
    width=264.0,
    height=65.0
)

canvas.create_text(
    829.0,
    841.0,
    anchor="nw",
    text="NestSafe v1.0",
    fill="#000000",
    font=("Noto Sans", 20 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    914.0,
    524.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=763.0,
    y=491.0,
    width=302.0,
    height=65.0
)

canvas.create_text(
    828.0,
    461.0,
    anchor="nw",
    text="Application",
    fill="#000000",
    font=("LexendDeca Bold", 24 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    914.0,
    630.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=763.0,
    y=597.0,
    width=302.0,
    height=65.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    914.0,
    415.5,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=763.0,
    y=382.0,
    width=302.0,
    height=65.0
)

canvas.create_text(
    840.0,
    567.0,
    anchor="nw",
    text="Password",
    fill="#000000",
    font=("LexendDeca Bold", 24 * -1)
)

canvas.create_text(
    837.0,
    348.0,
    anchor="nw",
    text="Username",
    fill="#000000",
    font=("LexendDeca Bold", 24 * -1)
)

canvas.create_text(
    702.0,
    291.0,
    anchor="nw",
    text="ADD A NEW RECORD",
    fill="#000000",
    font=("LexendDeca Bold", 36 * -1)
)
window.resizable(False, False)
window.mainloop()
